// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlMX104oshiWGizRxnoBbDBTwtNDZqn28',
    appId: '1:7493508024:web:35bb0e0348889b38168d4d',
    messagingSenderId: '7493508024',
    projectId: 'flutterchatapp-494e4',
    authDomain: 'flutterchatapp-494e4.firebaseapp.com',
    storageBucket: 'flutterchatapp-494e4.appspot.com',
    measurementId: 'G-9XR7EDSN9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMQCgkBzyJHm7lXP2WZCF2S1j770Zo36M',
    appId: '1:7493508024:android:994599e54dac8005168d4d',
    messagingSenderId: '7493508024',
    projectId: 'flutterchatapp-494e4',
    storageBucket: 'flutterchatapp-494e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw5wve9_i-PQJmltxoRz9AJ3VXKLOTvC0',
    appId: '1:7493508024:ios:b861dafd2e11f26e168d4d',
    messagingSenderId: '7493508024',
    projectId: 'flutterchatapp-494e4',
    storageBucket: 'flutterchatapp-494e4.appspot.com',
    iosClientId: '7493508024-h7g9lgkcvcjsasheu1uqmjprm2f1nov1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw5wve9_i-PQJmltxoRz9AJ3VXKLOTvC0',
    appId: '1:7493508024:ios:99f1814d241f7800168d4d',
    messagingSenderId: '7493508024',
    projectId: 'flutterchatapp-494e4',
    storageBucket: 'flutterchatapp-494e4.appspot.com',
    iosClientId: '7493508024-psk2c6m2lvqkd7vs7t0i9u45hei8aum4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
